// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

enum EmbeddingBackend {
  CPU,
  GPU,
  GPU_FLOAT16,
  GPU_MIXED,
}

class InitializeRequest {
  InitializeRequest({
    required this.modelPath,
    required this.tokenizerPath,
    required this.dimensions,
    required this.backend,
  });

  String modelPath;

  String tokenizerPath;

  int dimensions;

  EmbeddingBackend backend;

  Object encode() {
    return <Object?>[
      modelPath,
      tokenizerPath,
      dimensions,
      backend,
    ];
  }

  static InitializeRequest decode(Object result) {
    result as List<Object?>;
    return InitializeRequest(
      modelPath: result[0]! as String,
      tokenizerPath: result[1]! as String,
      dimensions: result[2]! as int,
      backend: result[3]! as EmbeddingBackend,
    );
  }
}

class InitializeResponse {
  InitializeResponse({
    required this.actualBackend,
  });

  EmbeddingBackend actualBackend;

  Object encode() {
    return <Object?>[
      actualBackend,
    ];
  }

  static InitializeResponse decode(Object result) {
    result as List<Object?>;
    return InitializeResponse(
      actualBackend: result[0]! as EmbeddingBackend,
    );
  }
}

class EmbedRequest {
  EmbedRequest({
    required this.text,
    required this.isQuery,
  });

  String text;

  bool isQuery;

  Object encode() {
    return <Object?>[
      text,
      isQuery,
    ];
  }

  static EmbedRequest decode(Object result) {
    result as List<Object?>;
    return EmbedRequest(
      text: result[0]! as String,
      isQuery: result[1]! as bool,
    );
  }
}

class EmbedBatchRequest {
  EmbedBatchRequest({
    required this.texts,
    required this.isQuery,
  });

  List<String> texts;

  bool isQuery;

  Object encode() {
    return <Object?>[
      texts,
      isQuery,
    ];
  }

  static EmbedBatchRequest decode(Object result) {
    result as List<Object?>;
    return EmbedBatchRequest(
      texts: (result[0] as List<Object?>?)!.cast<String>(),
      isQuery: result[1]! as bool,
    );
  }
}

class EmbeddingResult {
  EmbeddingResult({
    required this.embedding,
  });

  List<double> embedding;

  Object encode() {
    return <Object?>[
      embedding,
    ];
  }

  static EmbeddingResult decode(Object result) {
    result as List<Object?>;
    return EmbeddingResult(
      embedding: (result[0] as List<Object?>?)!.cast<double>(),
    );
  }
}

class BatchEmbeddingResult {
  BatchEmbeddingResult({
    required this.embeddings,
  });

  List<List<double>> embeddings;

  Object encode() {
    return <Object?>[
      embeddings,
    ];
  }

  static BatchEmbeddingResult decode(Object result) {
    result as List<Object?>;
    return BatchEmbeddingResult(
      embeddings: (result[0] as List<Object?>?)!.cast<List<double>>(),
    );
  }
}

class TokenCountRequest {
  TokenCountRequest({
    required this.text,
    required this.withPrompt,
  });

  String text;

  bool withPrompt;

  Object encode() {
    return <Object?>[
      text,
      withPrompt,
    ];
  }

  static TokenCountRequest decode(Object result) {
    result as List<Object?>;
    return TokenCountRequest(
      text: result[0]! as String,
      withPrompt: result[1]! as bool,
    );
  }
}

class TokenCountResult {
  TokenCountResult({
    required this.tokenCount,
  });

  int tokenCount;

  Object encode() {
    return <Object?>[
      tokenCount,
    ];
  }

  static TokenCountResult decode(Object result) {
    result as List<Object?>;
    return TokenCountResult(
      tokenCount: result[0]! as int,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is EmbeddingBackend) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is InitializeRequest) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is InitializeResponse) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is EmbedRequest) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is EmbedBatchRequest) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is EmbeddingResult) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is BatchEmbeddingResult) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is TokenCountRequest) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is TokenCountResult) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : EmbeddingBackend.values[value];
      case 130: 
        return InitializeRequest.decode(readValue(buffer)!);
      case 131: 
        return InitializeResponse.decode(readValue(buffer)!);
      case 132: 
        return EmbedRequest.decode(readValue(buffer)!);
      case 133: 
        return EmbedBatchRequest.decode(readValue(buffer)!);
      case 134: 
        return EmbeddingResult.decode(readValue(buffer)!);
      case 135: 
        return BatchEmbeddingResult.decode(readValue(buffer)!);
      case 136: 
        return TokenCountRequest.decode(readValue(buffer)!);
      case 137: 
        return TokenCountResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class EmbeddingGemmaApi {
  /// Constructor for [EmbeddingGemmaApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  EmbeddingGemmaApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<InitializeResponse> initialize(InitializeRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.embedding_gemma.EmbeddingGemmaApi.initialize$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[request]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as InitializeResponse?)!;
    }
  }

  Future<EmbeddingResult> embed(EmbedRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.embedding_gemma.EmbeddingGemmaApi.embed$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[request]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as EmbeddingResult?)!;
    }
  }

  Future<BatchEmbeddingResult> embedBatch(EmbedBatchRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.embedding_gemma.EmbeddingGemmaApi.embedBatch$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[request]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as BatchEmbeddingResult?)!;
    }
  }

  Future<TokenCountResult> countTokens(TokenCountRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.embedding_gemma.EmbeddingGemmaApi.countTokens$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[request]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as TokenCountResult?)!;
    }
  }

  Future<void> dispose() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.embedding_gemma.EmbeddingGemmaApi.dispose$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}
