// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum EmbeddingBackend: Int {
  case cPU = 0
  case gPU = 1
  case gPUFLOAT16 = 2
  case gPUMIXED = 3
}

/// Generated class from Pigeon that represents data sent in messages.
struct InitializeRequest {
  var modelPath: String
  var tokenizerPath: String
  var dimensions: Int64
  var backend: EmbeddingBackend


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> InitializeRequest? {
    let modelPath = pigeonVar_list[0] as! String
    let tokenizerPath = pigeonVar_list[1] as! String
    let dimensions = pigeonVar_list[2] as! Int64
    let backend = pigeonVar_list[3] as! EmbeddingBackend

    return InitializeRequest(
      modelPath: modelPath,
      tokenizerPath: tokenizerPath,
      dimensions: dimensions,
      backend: backend
    )
  }
  func toList() -> [Any?] {
    return [
      modelPath,
      tokenizerPath,
      dimensions,
      backend,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct InitializeResponse {
  var actualBackend: EmbeddingBackend


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> InitializeResponse? {
    let actualBackend = pigeonVar_list[0] as! EmbeddingBackend

    return InitializeResponse(
      actualBackend: actualBackend
    )
  }
  func toList() -> [Any?] {
    return [
      actualBackend
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct EmbedRequest {
  var text: String
  var isQuery: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EmbedRequest? {
    let text = pigeonVar_list[0] as! String
    let isQuery = pigeonVar_list[1] as! Bool

    return EmbedRequest(
      text: text,
      isQuery: isQuery
    )
  }
  func toList() -> [Any?] {
    return [
      text,
      isQuery,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct EmbedBatchRequest {
  var texts: [String]
  var isQuery: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EmbedBatchRequest? {
    let texts = pigeonVar_list[0] as! [String]
    let isQuery = pigeonVar_list[1] as! Bool

    return EmbedBatchRequest(
      texts: texts,
      isQuery: isQuery
    )
  }
  func toList() -> [Any?] {
    return [
      texts,
      isQuery,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct EmbeddingResult {
  var embedding: [Double]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EmbeddingResult? {
    let embedding = pigeonVar_list[0] as! [Double]

    return EmbeddingResult(
      embedding: embedding
    )
  }
  func toList() -> [Any?] {
    return [
      embedding
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BatchEmbeddingResult {
  var embeddings: [[Double]]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BatchEmbeddingResult? {
    let embeddings = pigeonVar_list[0] as! [[Double]]

    return BatchEmbeddingResult(
      embeddings: embeddings
    )
  }
  func toList() -> [Any?] {
    return [
      embeddings
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TokenCountRequest {
  var text: String
  var withPrompt: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TokenCountRequest? {
    let text = pigeonVar_list[0] as! String
    let withPrompt = pigeonVar_list[1] as! Bool

    return TokenCountRequest(
      text: text,
      withPrompt: withPrompt
    )
  }
  func toList() -> [Any?] {
    return [
      text,
      withPrompt,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TokenCountResult {
  var tokenCount: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TokenCountResult? {
    let tokenCount = pigeonVar_list[0] as! Int64

    return TokenCountResult(
      tokenCount: tokenCount
    )
  }
  func toList() -> [Any?] {
    return [
      tokenCount
    ]
  }
}

private class EmbeddingApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return EmbeddingBackend(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return InitializeRequest.fromList(self.readValue() as! [Any?])
    case 131:
      return InitializeResponse.fromList(self.readValue() as! [Any?])
    case 132:
      return EmbedRequest.fromList(self.readValue() as! [Any?])
    case 133:
      return EmbedBatchRequest.fromList(self.readValue() as! [Any?])
    case 134:
      return EmbeddingResult.fromList(self.readValue() as! [Any?])
    case 135:
      return BatchEmbeddingResult.fromList(self.readValue() as! [Any?])
    case 136:
      return TokenCountRequest.fromList(self.readValue() as! [Any?])
    case 137:
      return TokenCountResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class EmbeddingApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? EmbeddingBackend {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? InitializeRequest {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? InitializeResponse {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? EmbedRequest {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? EmbedBatchRequest {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? EmbeddingResult {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? BatchEmbeddingResult {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? TokenCountRequest {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? TokenCountResult {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class EmbeddingApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return EmbeddingApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return EmbeddingApiPigeonCodecWriter(data: data)
  }
}

class EmbeddingApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = EmbeddingApiPigeonCodec(readerWriter: EmbeddingApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol EmbeddingGemmaApi {
  func initialize(request: InitializeRequest, completion: @escaping (Result<InitializeResponse, Error>) -> Void)
  func embed(request: EmbedRequest, completion: @escaping (Result<EmbeddingResult, Error>) -> Void)
  func embedBatch(request: EmbedBatchRequest, completion: @escaping (Result<BatchEmbeddingResult, Error>) -> Void)
  func countTokens(request: TokenCountRequest, completion: @escaping (Result<TokenCountResult, Error>) -> Void)
  func dispose() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class EmbeddingGemmaApiSetup {
  static var codec: FlutterStandardMessageCodec { EmbeddingApiPigeonCodec.shared }
  /// Sets up an instance of `EmbeddingGemmaApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: EmbeddingGemmaApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.embedding_gemma.EmbeddingGemmaApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! InitializeRequest
        api.initialize(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let embedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.embedding_gemma.EmbeddingGemmaApi.embed\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      embedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! EmbedRequest
        api.embed(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      embedChannel.setMessageHandler(nil)
    }
    let embedBatchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.embedding_gemma.EmbeddingGemmaApi.embedBatch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      embedBatchChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! EmbedBatchRequest
        api.embedBatch(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      embedBatchChannel.setMessageHandler(nil)
    }
    let countTokensChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.embedding_gemma.EmbeddingGemmaApi.countTokens\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      countTokensChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! TokenCountRequest
        api.countTokens(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      countTokensChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.embedding_gemma.EmbeddingGemmaApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        do {
          try api.dispose()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
  }
}
