// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'domain/entities/chunk.dart';
import 'domain/entities/conversation.dart';
import 'domain/entities/material.dart';
import 'domain/entities/message.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1014927944962503315),
    name: 'Chunk',
    lastPropertyId: const obx_int.IdUid(10, 5588954731300215075),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6709185899553073650),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7773328921561976673),
        name: 'materialId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 5439872051914313344),
        relationField: 'material',
        relationTarget: 'Material',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4305073666865688410),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5510307796690759285),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(2, 8378665914255442732),
        hnswParams: obx_int.ModelHnswParams(
          dimensions: 768,
          neighborsPerNode: 30,
          indexingSearchCount: 200,
        ),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3582159046973216790),
        name: 'pageNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3015122487044844625),
        name: 'sectionIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2482724341437920654),
        name: 'sequenceIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1116029466652993313),
        name: 'chunkType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6972437144866282369),
        name: 'wordCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5588954731300215075),
        name: 'metadataJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 1275461671198510520),
    name: 'Conversation',
    lastPropertyId: const obx_int.IdUid(6, 3999185776919199178),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4587172284961096259),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6972628384433793470),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8363438003544894210),
        name: 'materialId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 7433102798156909775),
        relationField: 'material',
        relationTarget: 'Material',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6602951435784386103),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 178783115204402322),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3999185776919199178),
        name: 'messageCount',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6019905763468012353),
    name: 'Material',
    lastPropertyId: const obx_int.IdUid(12, 6907678506623526696),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3618742304875008395),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8000636856101579643),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 143022550970611100),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5027614071441482981),
        name: 'originalFilePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5205405654895537032),
        name: 'sourceType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1677240073368449816),
        name: 'subject',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7103782152128674443),
        name: 'gradeLevel',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6162553733696263270),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6435690315599425260),
        name: 'errorMessage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4989819606414773769),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 83910163105170219),
        name: 'processedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6907678506623526696),
        name: 'chunkCount',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 8744402169022907611),
    name: 'Message',
    lastPropertyId: const obx_int.IdUid(8, 654517624235125786),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6052503138091622903),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2168596518520771867),
        name: 'conversationId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 9063384396148918469),
        relationField: 'conversation',
        relationTarget: 'Conversation',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3125831741675143473),
        name: 'role',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4837281770268361817),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7900289977270552081),
        name: 'retrievedChunkIds',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 69476831823727716),
        name: 'confidenceScore',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2393227237054457206),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 654517624235125786),
        name: 'sequenceIndex',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 8744402169022907611),
    lastIndexId: const obx_int.IdUid(4, 9063384396148918469),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Chunk: obx_int.EntityDefinition<Chunk>(
      model: _entities[0],
      toOneRelations: (Chunk object) => [object.material],
      toManyRelations: (Chunk object) => {},
      getId: (Chunk object) => object.id,
      setId: (Chunk object, int id) {
        object.id = id;
      },
      objectToFB: (Chunk object, fb.Builder fbb) {
        final contentOffset = fbb.writeString(object.content);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        final chunkTypeOffset = fbb.writeString(object.chunkType);
        final metadataJsonOffset = object.metadataJson == null
            ? null
            : fbb.writeString(object.metadataJson!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.material.targetId);
        fbb.addOffset(2, contentOffset);
        fbb.addOffset(3, embeddingOffset);
        fbb.addInt64(4, object.pageNumber);
        fbb.addInt64(5, object.sectionIndex);
        fbb.addInt64(6, object.sequenceIndex);
        fbb.addOffset(7, chunkTypeOffset);
        fbb.addInt64(8, object.wordCount);
        fbb.addOffset(9, metadataJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final pageNumberParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final sectionIndexParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final sequenceIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final chunkTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final wordCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final metadataJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final object = Chunk(
          content: contentParam,
          embedding: embeddingParam,
          pageNumber: pageNumberParam,
          sectionIndex: sectionIndexParam,
          sequenceIndex: sequenceIndexParam,
          chunkType: chunkTypeParam,
          wordCount: wordCountParam,
          metadataJson: metadataJsonParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.material.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.material.attach(store);
        return object;
      },
    ),
    Conversation: obx_int.EntityDefinition<Conversation>(
      model: _entities[1],
      toOneRelations: (Conversation object) => [object.material],
      toManyRelations: (Conversation object) => {},
      getId: (Conversation object) => object.id,
      setId: (Conversation object, int id) {
        object.id = id;
      },
      objectToFB: (Conversation object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addInt64(2, object.material.targetId);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(5, object.messageCount);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final messageCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = Conversation(
          title: titleParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          messageCount: messageCountParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.material.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.material.attach(store);
        return object;
      },
    ),
    Material: obx_int.EntityDefinition<Material>(
      model: _entities[2],
      toOneRelations: (Material object) => [],
      toManyRelations: (Material object) => {},
      getId: (Material object) => object.id,
      setId: (Material object, int id) {
        object.id = id;
      },
      objectToFB: (Material object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final originalFilePathOffset = object.originalFilePath == null
            ? null
            : fbb.writeString(object.originalFilePath!);
        final sourceTypeOffset = fbb.writeString(object.sourceType);
        final subjectOffset = object.subject == null
            ? null
            : fbb.writeString(object.subject!);
        final statusOffset = fbb.writeString(object.status);
        final errorMessageOffset = object.errorMessage == null
            ? null
            : fbb.writeString(object.errorMessage!);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, originalFilePathOffset);
        fbb.addOffset(4, sourceTypeOffset);
        fbb.addOffset(5, subjectOffset);
        fbb.addInt64(6, object.gradeLevel);
        fbb.addOffset(7, statusOffset);
        fbb.addOffset(8, errorMessageOffset);
        fbb.addInt64(9, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(10, object.processedAt?.millisecondsSinceEpoch);
        fbb.addInt64(11, object.chunkCount);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final processedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          24,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final originalFilePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final sourceTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final subjectParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final gradeLevelParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final errorMessageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final processedAtParam = processedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(processedAtValue);
        final chunkCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final object = Material(
          title: titleParam,
          description: descriptionParam,
          originalFilePath: originalFilePathParam,
          sourceType: sourceTypeParam,
          subject: subjectParam,
          gradeLevel: gradeLevelParam,
          status: statusParam,
          errorMessage: errorMessageParam,
          createdAt: createdAtParam,
          processedAt: processedAtParam,
          chunkCount: chunkCountParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    Message: obx_int.EntityDefinition<Message>(
      model: _entities[3],
      toOneRelations: (Message object) => [object.conversation],
      toManyRelations: (Message object) => {},
      getId: (Message object) => object.id,
      setId: (Message object, int id) {
        object.id = id;
      },
      objectToFB: (Message object, fb.Builder fbb) {
        final roleOffset = fbb.writeString(object.role);
        final contentOffset = fbb.writeString(object.content);
        final retrievedChunkIdsOffset = object.retrievedChunkIds == null
            ? null
            : fbb.writeString(object.retrievedChunkIds!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.conversation.targetId);
        fbb.addOffset(2, roleOffset);
        fbb.addOffset(3, contentOffset);
        fbb.addOffset(4, retrievedChunkIdsOffset);
        fbb.addFloat64(5, object.confidenceScore);
        fbb.addInt64(6, object.timestamp.millisecondsSinceEpoch);
        fbb.addInt64(7, object.sequenceIndex);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final roleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final retrievedChunkIdsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final confidenceScoreParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final sequenceIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final object = Message(
          role: roleParam,
          content: contentParam,
          retrievedChunkIds: retrievedChunkIdsParam,
          confidenceScore: confidenceScoreParam,
          timestamp: timestampParam,
          sequenceIndex: sequenceIndexParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.conversation.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.conversation.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Chunk] entity fields to define ObjectBox queries.
class Chunk_ {
  /// See [Chunk.id].
  static final id = obx.QueryIntegerProperty<Chunk>(_entities[0].properties[0]);

  /// See [Chunk.material].
  static final material = obx.QueryRelationToOne<Chunk, Material>(
    _entities[0].properties[1],
  );

  /// See [Chunk.content].
  static final content = obx.QueryStringProperty<Chunk>(
    _entities[0].properties[2],
  );

  /// See [Chunk.embedding].
  static final embedding = obx.QueryHnswProperty<Chunk>(
    _entities[0].properties[3],
  );

  /// See [Chunk.pageNumber].
  static final pageNumber = obx.QueryIntegerProperty<Chunk>(
    _entities[0].properties[4],
  );

  /// See [Chunk.sectionIndex].
  static final sectionIndex = obx.QueryIntegerProperty<Chunk>(
    _entities[0].properties[5],
  );

  /// See [Chunk.sequenceIndex].
  static final sequenceIndex = obx.QueryIntegerProperty<Chunk>(
    _entities[0].properties[6],
  );

  /// See [Chunk.chunkType].
  static final chunkType = obx.QueryStringProperty<Chunk>(
    _entities[0].properties[7],
  );

  /// See [Chunk.wordCount].
  static final wordCount = obx.QueryIntegerProperty<Chunk>(
    _entities[0].properties[8],
  );

  /// See [Chunk.metadataJson].
  static final metadataJson = obx.QueryStringProperty<Chunk>(
    _entities[0].properties[9],
  );
}

/// [Conversation] entity fields to define ObjectBox queries.
class Conversation_ {
  /// See [Conversation.id].
  static final id = obx.QueryIntegerProperty<Conversation>(
    _entities[1].properties[0],
  );

  /// See [Conversation.title].
  static final title = obx.QueryStringProperty<Conversation>(
    _entities[1].properties[1],
  );

  /// See [Conversation.material].
  static final material = obx.QueryRelationToOne<Conversation, Material>(
    _entities[1].properties[2],
  );

  /// See [Conversation.createdAt].
  static final createdAt = obx.QueryDateProperty<Conversation>(
    _entities[1].properties[3],
  );

  /// See [Conversation.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Conversation>(
    _entities[1].properties[4],
  );

  /// See [Conversation.messageCount].
  static final messageCount = obx.QueryIntegerProperty<Conversation>(
    _entities[1].properties[5],
  );
}

/// [Material] entity fields to define ObjectBox queries.
class Material_ {
  /// See [Material.id].
  static final id = obx.QueryIntegerProperty<Material>(
    _entities[2].properties[0],
  );

  /// See [Material.title].
  static final title = obx.QueryStringProperty<Material>(
    _entities[2].properties[1],
  );

  /// See [Material.description].
  static final description = obx.QueryStringProperty<Material>(
    _entities[2].properties[2],
  );

  /// See [Material.originalFilePath].
  static final originalFilePath = obx.QueryStringProperty<Material>(
    _entities[2].properties[3],
  );

  /// See [Material.sourceType].
  static final sourceType = obx.QueryStringProperty<Material>(
    _entities[2].properties[4],
  );

  /// See [Material.subject].
  static final subject = obx.QueryStringProperty<Material>(
    _entities[2].properties[5],
  );

  /// See [Material.gradeLevel].
  static final gradeLevel = obx.QueryIntegerProperty<Material>(
    _entities[2].properties[6],
  );

  /// See [Material.status].
  static final status = obx.QueryStringProperty<Material>(
    _entities[2].properties[7],
  );

  /// See [Material.errorMessage].
  static final errorMessage = obx.QueryStringProperty<Material>(
    _entities[2].properties[8],
  );

  /// See [Material.createdAt].
  static final createdAt = obx.QueryDateProperty<Material>(
    _entities[2].properties[9],
  );

  /// See [Material.processedAt].
  static final processedAt = obx.QueryDateProperty<Material>(
    _entities[2].properties[10],
  );

  /// See [Material.chunkCount].
  static final chunkCount = obx.QueryIntegerProperty<Material>(
    _entities[2].properties[11],
  );
}

/// [Message] entity fields to define ObjectBox queries.
class Message_ {
  /// See [Message.id].
  static final id = obx.QueryIntegerProperty<Message>(
    _entities[3].properties[0],
  );

  /// See [Message.conversation].
  static final conversation = obx.QueryRelationToOne<Message, Conversation>(
    _entities[3].properties[1],
  );

  /// See [Message.role].
  static final role = obx.QueryStringProperty<Message>(
    _entities[3].properties[2],
  );

  /// See [Message.content].
  static final content = obx.QueryStringProperty<Message>(
    _entities[3].properties[3],
  );

  /// See [Message.retrievedChunkIds].
  static final retrievedChunkIds = obx.QueryStringProperty<Message>(
    _entities[3].properties[4],
  );

  /// See [Message.confidenceScore].
  static final confidenceScore = obx.QueryDoubleProperty<Message>(
    _entities[3].properties[5],
  );

  /// See [Message.timestamp].
  static final timestamp = obx.QueryDateProperty<Message>(
    _entities[3].properties[6],
  );

  /// See [Message.sequenceIndex].
  static final sequenceIndex = obx.QueryIntegerProperty<Message>(
    _entities[3].properties[7],
  );
}
