// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'domain/entities/chunk.dart';
import 'domain/entities/conversation.dart';
import 'domain/entities/material.dart';
import 'domain/entities/message.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4048550045256450929),
    name: 'Chunk',
    lastPropertyId: const obx_int.IdUid(10, 40019808939853998),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5186621587242797281),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1464852401326240154),
        name: 'materialId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 2626460588379721848),
        relationField: 'material',
        relationTarget: 'Material',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7164744722580448601),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1949481921866950909),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(2, 7083483831641117470),
        hnswParams: obx_int.ModelHnswParams(
          dimensions: 768,
          neighborsPerNode: 30,
          indexingSearchCount: 200,
        ),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6270241338273359099),
        name: 'pageNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3801740604640510720),
        name: 'sectionIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5711535661525823872),
        name: 'sequenceIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 313174752908618443),
        name: 'chunkType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1730907117097515167),
        name: 'wordCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 40019808939853998),
        name: 'metadataJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 3508608066664415253),
    name: 'Conversation',
    lastPropertyId: const obx_int.IdUid(6, 8306741551361702313),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8341343898410331298),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3482781884614899195),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2988829466435394634),
        name: 'materialId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 8372028186160909134),
        relationField: 'material',
        relationTarget: 'Material',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4907962663730007657),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6622244373963247212),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8306741551361702313),
        name: 'messageCount',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6080377325167891588),
    name: 'Material',
    lastPropertyId: const obx_int.IdUid(12, 397661219195387232),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7279095742952335095),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6198473928457602490),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3218065543476788113),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4643392275195755402),
        name: 'originalFilePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8964006159146065474),
        name: 'sourceType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5970615035879835017),
        name: 'subject',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6868581749154477040),
        name: 'gradeLevel',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5227166602899661438),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7610273914089401933),
        name: 'errorMessage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2540494431064441104),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1902148016737999927),
        name: 'processedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 397661219195387232),
        name: 'chunkCount',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 8466680942746594316),
    name: 'Message',
    lastPropertyId: const obx_int.IdUid(8, 136530563011414877),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 858311097694291831),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1544822232593814083),
        name: 'conversationId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 4452394715110665154),
        relationField: 'conversation',
        relationTarget: 'Conversation',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 989797639163743407),
        name: 'role',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 673444267618009432),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 524046887560705998),
        name: 'retrievedChunkIds',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8965926854287124627),
        name: 'confidenceScore',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8932176986023524643),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 136530563011414877),
        name: 'sequenceIndex',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 8466680942746594316),
    lastIndexId: const obx_int.IdUid(4, 4452394715110665154),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Chunk: obx_int.EntityDefinition<Chunk>(
      model: _entities[0],
      toOneRelations: (Chunk object) => [object.material],
      toManyRelations: (Chunk object) => {},
      getId: (Chunk object) => object.id,
      setId: (Chunk object, int id) {
        object.id = id;
      },
      objectToFB: (Chunk object, fb.Builder fbb) {
        final contentOffset = fbb.writeString(object.content);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        final chunkTypeOffset = fbb.writeString(object.chunkType);
        final metadataJsonOffset = object.metadataJson == null
            ? null
            : fbb.writeString(object.metadataJson!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.material.targetId);
        fbb.addOffset(2, contentOffset);
        fbb.addOffset(3, embeddingOffset);
        fbb.addInt64(4, object.pageNumber);
        fbb.addInt64(5, object.sectionIndex);
        fbb.addInt64(6, object.sequenceIndex);
        fbb.addOffset(7, chunkTypeOffset);
        fbb.addInt64(8, object.wordCount);
        fbb.addOffset(9, metadataJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final pageNumberParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final sectionIndexParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final sequenceIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final chunkTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final wordCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final metadataJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final object = Chunk(
          content: contentParam,
          embedding: embeddingParam,
          pageNumber: pageNumberParam,
          sectionIndex: sectionIndexParam,
          sequenceIndex: sequenceIndexParam,
          chunkType: chunkTypeParam,
          wordCount: wordCountParam,
          metadataJson: metadataJsonParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.material.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.material.attach(store);
        return object;
      },
    ),
    Conversation: obx_int.EntityDefinition<Conversation>(
      model: _entities[1],
      toOneRelations: (Conversation object) => [object.material],
      toManyRelations: (Conversation object) => {},
      getId: (Conversation object) => object.id,
      setId: (Conversation object, int id) {
        object.id = id;
      },
      objectToFB: (Conversation object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addInt64(2, object.material.targetId);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(5, object.messageCount);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final messageCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = Conversation(
          title: titleParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          messageCount: messageCountParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.material.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.material.attach(store);
        return object;
      },
    ),
    Material: obx_int.EntityDefinition<Material>(
      model: _entities[2],
      toOneRelations: (Material object) => [],
      toManyRelations: (Material object) => {},
      getId: (Material object) => object.id,
      setId: (Material object, int id) {
        object.id = id;
      },
      objectToFB: (Material object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final originalFilePathOffset = object.originalFilePath == null
            ? null
            : fbb.writeString(object.originalFilePath!);
        final sourceTypeOffset = fbb.writeString(object.sourceType);
        final subjectOffset = object.subject == null
            ? null
            : fbb.writeString(object.subject!);
        final statusOffset = fbb.writeString(object.status);
        final errorMessageOffset = object.errorMessage == null
            ? null
            : fbb.writeString(object.errorMessage!);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, originalFilePathOffset);
        fbb.addOffset(4, sourceTypeOffset);
        fbb.addOffset(5, subjectOffset);
        fbb.addInt64(6, object.gradeLevel);
        fbb.addOffset(7, statusOffset);
        fbb.addOffset(8, errorMessageOffset);
        fbb.addInt64(9, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(10, object.processedAt?.millisecondsSinceEpoch);
        fbb.addInt64(11, object.chunkCount);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final processedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          24,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final originalFilePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final sourceTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final subjectParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final gradeLevelParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final errorMessageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final processedAtParam = processedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(processedAtValue);
        final chunkCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final object = Material(
          title: titleParam,
          description: descriptionParam,
          originalFilePath: originalFilePathParam,
          sourceType: sourceTypeParam,
          subject: subjectParam,
          gradeLevel: gradeLevelParam,
          status: statusParam,
          errorMessage: errorMessageParam,
          createdAt: createdAtParam,
          processedAt: processedAtParam,
          chunkCount: chunkCountParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    Message: obx_int.EntityDefinition<Message>(
      model: _entities[3],
      toOneRelations: (Message object) => [object.conversation],
      toManyRelations: (Message object) => {},
      getId: (Message object) => object.id,
      setId: (Message object, int id) {
        object.id = id;
      },
      objectToFB: (Message object, fb.Builder fbb) {
        final roleOffset = fbb.writeString(object.role);
        final contentOffset = fbb.writeString(object.content);
        final retrievedChunkIdsOffset = object.retrievedChunkIds == null
            ? null
            : fbb.writeString(object.retrievedChunkIds!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.conversation.targetId);
        fbb.addOffset(2, roleOffset);
        fbb.addOffset(3, contentOffset);
        fbb.addOffset(4, retrievedChunkIdsOffset);
        fbb.addFloat64(5, object.confidenceScore);
        fbb.addInt64(6, object.timestamp.millisecondsSinceEpoch);
        fbb.addInt64(7, object.sequenceIndex);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final roleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final retrievedChunkIdsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final confidenceScoreParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final sequenceIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final object = Message(
          role: roleParam,
          content: contentParam,
          retrievedChunkIds: retrievedChunkIdsParam,
          confidenceScore: confidenceScoreParam,
          timestamp: timestampParam,
          sequenceIndex: sequenceIndexParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.conversation.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.conversation.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Chunk] entity fields to define ObjectBox queries.
class Chunk_ {
  /// See [Chunk.id].
  static final id = obx.QueryIntegerProperty<Chunk>(_entities[0].properties[0]);

  /// See [Chunk.material].
  static final material = obx.QueryRelationToOne<Chunk, Material>(
    _entities[0].properties[1],
  );

  /// See [Chunk.content].
  static final content = obx.QueryStringProperty<Chunk>(
    _entities[0].properties[2],
  );

  /// See [Chunk.embedding].
  static final embedding = obx.QueryHnswProperty<Chunk>(
    _entities[0].properties[3],
  );

  /// See [Chunk.pageNumber].
  static final pageNumber = obx.QueryIntegerProperty<Chunk>(
    _entities[0].properties[4],
  );

  /// See [Chunk.sectionIndex].
  static final sectionIndex = obx.QueryIntegerProperty<Chunk>(
    _entities[0].properties[5],
  );

  /// See [Chunk.sequenceIndex].
  static final sequenceIndex = obx.QueryIntegerProperty<Chunk>(
    _entities[0].properties[6],
  );

  /// See [Chunk.chunkType].
  static final chunkType = obx.QueryStringProperty<Chunk>(
    _entities[0].properties[7],
  );

  /// See [Chunk.wordCount].
  static final wordCount = obx.QueryIntegerProperty<Chunk>(
    _entities[0].properties[8],
  );

  /// See [Chunk.metadataJson].
  static final metadataJson = obx.QueryStringProperty<Chunk>(
    _entities[0].properties[9],
  );
}

/// [Conversation] entity fields to define ObjectBox queries.
class Conversation_ {
  /// See [Conversation.id].
  static final id = obx.QueryIntegerProperty<Conversation>(
    _entities[1].properties[0],
  );

  /// See [Conversation.title].
  static final title = obx.QueryStringProperty<Conversation>(
    _entities[1].properties[1],
  );

  /// See [Conversation.material].
  static final material = obx.QueryRelationToOne<Conversation, Material>(
    _entities[1].properties[2],
  );

  /// See [Conversation.createdAt].
  static final createdAt = obx.QueryDateProperty<Conversation>(
    _entities[1].properties[3],
  );

  /// See [Conversation.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Conversation>(
    _entities[1].properties[4],
  );

  /// See [Conversation.messageCount].
  static final messageCount = obx.QueryIntegerProperty<Conversation>(
    _entities[1].properties[5],
  );
}

/// [Material] entity fields to define ObjectBox queries.
class Material_ {
  /// See [Material.id].
  static final id = obx.QueryIntegerProperty<Material>(
    _entities[2].properties[0],
  );

  /// See [Material.title].
  static final title = obx.QueryStringProperty<Material>(
    _entities[2].properties[1],
  );

  /// See [Material.description].
  static final description = obx.QueryStringProperty<Material>(
    _entities[2].properties[2],
  );

  /// See [Material.originalFilePath].
  static final originalFilePath = obx.QueryStringProperty<Material>(
    _entities[2].properties[3],
  );

  /// See [Material.sourceType].
  static final sourceType = obx.QueryStringProperty<Material>(
    _entities[2].properties[4],
  );

  /// See [Material.subject].
  static final subject = obx.QueryStringProperty<Material>(
    _entities[2].properties[5],
  );

  /// See [Material.gradeLevel].
  static final gradeLevel = obx.QueryIntegerProperty<Material>(
    _entities[2].properties[6],
  );

  /// See [Material.status].
  static final status = obx.QueryStringProperty<Material>(
    _entities[2].properties[7],
  );

  /// See [Material.errorMessage].
  static final errorMessage = obx.QueryStringProperty<Material>(
    _entities[2].properties[8],
  );

  /// See [Material.createdAt].
  static final createdAt = obx.QueryDateProperty<Material>(
    _entities[2].properties[9],
  );

  /// See [Material.processedAt].
  static final processedAt = obx.QueryDateProperty<Material>(
    _entities[2].properties[10],
  );

  /// See [Material.chunkCount].
  static final chunkCount = obx.QueryIntegerProperty<Material>(
    _entities[2].properties[11],
  );
}

/// [Message] entity fields to define ObjectBox queries.
class Message_ {
  /// See [Message.id].
  static final id = obx.QueryIntegerProperty<Message>(
    _entities[3].properties[0],
  );

  /// See [Message.conversation].
  static final conversation = obx.QueryRelationToOne<Message, Conversation>(
    _entities[3].properties[1],
  );

  /// See [Message.role].
  static final role = obx.QueryStringProperty<Message>(
    _entities[3].properties[2],
  );

  /// See [Message.content].
  static final content = obx.QueryStringProperty<Message>(
    _entities[3].properties[3],
  );

  /// See [Message.retrievedChunkIds].
  static final retrievedChunkIds = obx.QueryStringProperty<Message>(
    _entities[3].properties[4],
  );

  /// See [Message.confidenceScore].
  static final confidenceScore = obx.QueryDoubleProperty<Message>(
    _entities[3].properties[5],
  );

  /// See [Message.timestamp].
  static final timestamp = obx.QueryDateProperty<Message>(
    _entities[3].properties[6],
  );

  /// See [Message.sequenceIndex].
  static final sequenceIndex = obx.QueryIntegerProperty<Message>(
    _entities[3].properties[7],
  );
}
