// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.flutter.embedding_gemma

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class EmbeddingBackend(val raw: Int) {
  CPU(0),
  GPU(1),
  GPU_FLOAT16(2),
  GPU_MIXED(3);

  companion object {
    fun ofRaw(raw: Int): EmbeddingBackend? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class InitializeRequest (
  val modelPath: String,
  val tokenizerPath: String,
  val dimensions: Long,
  val backend: EmbeddingBackend
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InitializeRequest {
      val modelPath = pigeonVar_list[0] as String
      val tokenizerPath = pigeonVar_list[1] as String
      val dimensions = pigeonVar_list[2] as Long
      val backend = pigeonVar_list[3] as EmbeddingBackend
      return InitializeRequest(modelPath, tokenizerPath, dimensions, backend)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      modelPath,
      tokenizerPath,
      dimensions,
      backend,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class InitializeResponse (
  val actualBackend: EmbeddingBackend
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InitializeResponse {
      val actualBackend = pigeonVar_list[0] as EmbeddingBackend
      return InitializeResponse(actualBackend)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      actualBackend,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class EmbedRequest (
  val text: String,
  val isQuery: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EmbedRequest {
      val text = pigeonVar_list[0] as String
      val isQuery = pigeonVar_list[1] as Boolean
      return EmbedRequest(text, isQuery)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      text,
      isQuery,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class EmbedBatchRequest (
  val texts: List<String>,
  val isQuery: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EmbedBatchRequest {
      val texts = pigeonVar_list[0] as List<String>
      val isQuery = pigeonVar_list[1] as Boolean
      return EmbedBatchRequest(texts, isQuery)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      texts,
      isQuery,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class EmbeddingResult (
  val embedding: List<Double>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EmbeddingResult {
      val embedding = pigeonVar_list[0] as List<Double>
      return EmbeddingResult(embedding)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      embedding,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BatchEmbeddingResult (
  val embeddings: List<List<Double>>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BatchEmbeddingResult {
      val embeddings = pigeonVar_list[0] as List<List<Double>>
      return BatchEmbeddingResult(embeddings)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      embeddings,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TokenCountRequest (
  val text: String,
  val withPrompt: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TokenCountRequest {
      val text = pigeonVar_list[0] as String
      val withPrompt = pigeonVar_list[1] as Boolean
      return TokenCountRequest(text, withPrompt)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      text,
      withPrompt,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TokenCountResult (
  val tokenCount: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TokenCountResult {
      val tokenCount = pigeonVar_list[0] as Long
      return TokenCountResult(tokenCount)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      tokenCount,
    )
  }
}
private open class EmbeddingApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          EmbeddingBackend.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InitializeRequest.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InitializeResponse.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EmbedRequest.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EmbedBatchRequest.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EmbeddingResult.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BatchEmbeddingResult.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TokenCountRequest.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TokenCountResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is EmbeddingBackend -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is InitializeRequest -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is InitializeResponse -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is EmbedRequest -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is EmbedBatchRequest -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is EmbeddingResult -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is BatchEmbeddingResult -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is TokenCountRequest -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is TokenCountResult -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface EmbeddingGemmaApi {
  fun initialize(request: InitializeRequest, callback: (Result<InitializeResponse>) -> Unit)
  fun embed(request: EmbedRequest, callback: (Result<EmbeddingResult>) -> Unit)
  fun embedBatch(request: EmbedBatchRequest, callback: (Result<BatchEmbeddingResult>) -> Unit)
  fun countTokens(request: TokenCountRequest, callback: (Result<TokenCountResult>) -> Unit)
  fun dispose()

  companion object {
    /** The codec used by EmbeddingGemmaApi. */
    val codec: MessageCodec<Any?> by lazy {
      EmbeddingApiPigeonCodec()
    }
    /** Sets up an instance of `EmbeddingGemmaApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: EmbeddingGemmaApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.embedding_gemma.EmbeddingGemmaApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as InitializeRequest
            api.initialize(requestArg) { result: Result<InitializeResponse> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.embedding_gemma.EmbeddingGemmaApi.embed$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as EmbedRequest
            api.embed(requestArg) { result: Result<EmbeddingResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.embedding_gemma.EmbeddingGemmaApi.embedBatch$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as EmbedBatchRequest
            api.embedBatch(requestArg) { result: Result<BatchEmbeddingResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.embedding_gemma.EmbeddingGemmaApi.countTokens$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as TokenCountRequest
            api.countTokens(requestArg) { result: Result<TokenCountResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.embedding_gemma.EmbeddingGemmaApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.dispose()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
